Example transport path
bobluppes/graaf pull request #47
Opened 2023-08-01 20:21 UTC by Hromz

First simple example

2023-08-05 14:14 UTC, bobluppes requested changes
Thanks for working on this, looks quite good already! 

I like your example graph, as it lends itself well for demonstrating the selected algorithms. I was thinking if we could change some of the vertex/edge data to make the example more realistic, let me know what you think about this.

2023-08-05 14:14 UTC, bobluppes commented on docs/docs/examples/example-basics/transport-example.md
> +
[minor]: In general I would avoid directly referencing line numbers in source files as this is subjective to change quite often.
```suggestion

Creating a vertex callback structure that will be passed as an argument in the graph traverse function
The function is needed in order to be called inside the traverse function; see graph.tpp for context.

```

2023-08-05 14:14 UTC, bobluppes commented on docs/docs/examples/example-basics/transport-example.md
> +```
I think the results from your BFS graph traversal are missing here. For instance, the `example_traversed_graph_BFS.png` is not added in this markdown file.

2023-08-05 14:14 UTC, bobluppes commented on examples/transport/main.cpp
> +};
[minor]: I know this code works currently, but ideally the road struct should derive from `weighted_edge`  and override the `get_weight` method. This is a design flaw on the weighted edge design, which I plan to address in a separate PR. 

For now, I would do the following;

```suggestion
struct road : public weighted_edge<int> {
  int length{};
  [[nodiscard]] int get_weight() const noexcept override { return length; }
};
```

2023-08-05 21:32 UTC, bobluppes commented
FYI, I merged quite a few breaking changes to the `graaf` interface on main. I pushed the changes to your branch, so you should be able to continue (after pulling your branch) without any merge conflicts. Please feel free to reach out if you encounter any issues.

2023-08-13 06:38 UTC, Hromz commented
Hey @bobluppes! Can you take a look? For some reason compile and test doesnt pass but it works fine on my machine. I've checked the error and it's saying that cannot find breadth traversal.

2023-08-13 11:56 UTC, bobluppes approved these changes
Thanks for working on this, looks great! I really like the example with the station names 🚀  

The CI issue turned out to be a conflict after merging main (which the CI does before running the workflows). On main I implemented our idea of changed the BFS/DFS callback to record traversed edges rather than vertices. I merged main on your branch and adjusted the callback accordingly.

2023-08-13 11:57 UTC, merged